[package]
name = "egui-fltk-frontend"
version = "0.3.3"
edition = "2018"
authors = ["Ar37-rs <adyaro37@gmail.com>"]
description = "FLTK frontend for Egui WGPU backend"
documentation = "https://docs.rs/egui-fltk-frontend"
readme = "README.md"
keywords = ["GUI", "egui", "fltk", "wgpu"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Ar37-rs/egui-fltk-frontend"
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.15"
egui_wgpu_backend = "0.14"
fltk = { version = "1.2", features = ["raw-window-handle"] }

[target."cfg(windows)".dependencies.copypasta]
version = "0.7"
optional = true

[target."cfg(all(unix, not(any(target_os=\"linux\", target_os=\"freebsd\"))))".dependencies.copypasta]
version = "0.7"
optional = true

[target."cfg(all(unix, any(target_os=\"linux\", target_os=\"freebsd\")))".dependencies.copypasta]
version = "0.7"
optional = true
default-features = false

[dependencies.tiny-skia]
version = "0.6"
optional = true

[dependencies.usvg]
version = "0.19"
optional = true

[dependencies.resvg]
version = "0.19"
optional = true

[features]
default = ["clipboard-x11"]
svg = ["resvg", "usvg", "tiny-skia"]
clipboard = ["copypasta"]
clipboard-x11 = ["clipboard", "copypasta/x11"]
clipboard-wayland = ["clipboard", "copypasta/wayland"]
fltk-bundled = ["fltk/fltk-bundled"]

[dev-dependencies]
egui_demo_lib = "0.15"
pollster = "0.2"