[package]
name = "main_example"
version = "0.3.0"
edition = "2018"
authors = ["Ar37-rs <adyaro37@gmail.com>"]
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# WGPU requires cargo resolver v2
resolver = "2"

[dependencies]
# with fltk-bundled features work on windows, linux and mac x64 only
# egui-fltk-frontend = { path = "../../../egui-fltk-frontend", features = ["fltk-bundled"] }
# On x11
# egui-fltk-frontend = { version = "0.3", default-features=false, features = ["clipboard-x11"] }
egui-fltk-frontend = "0.3"
egui_demo_lib = "0.15"
egui_wgpu_backend = "0.14"
pollster = "0.2"
