[package]
name = "main_example"
version = "0.1.0"
edition = "2018"
authors = ["Ar37-rs <adyaro37@gmail.com>"]
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# WGPU requires cargo resolver v2
resolver = "2"

[dependencies]
egui_demo_lib = "0.14"
egui_wgpu_backend = "0.13"
# with fltk-bundled features work on windows, linux and mac x64 only
egui-fltk-frontend = { path = "../../../egui-fltk-frontend", features = ["fltk-bundled"]}
pollster = "0.2"